In [5]:
import pandas as pd
import numpy as np

In [6]:
orde = pd.read_csv('../Proyecto_Kaggle/data/train.csv')

In [3]:
orde.head()

Manufacturer   Model Name   Category Screen Size   
0        Apple  MacBook Pro  Ultrabook       13.3"  \
1        Apple  Macbook Air  Ultrabook       13.3"   
2           HP       250 G6   Notebook       15.6"   
3        Apple  MacBook Pro  Ultrabook       15.4"   
4        Apple  MacBook Pro  Ultrabook       13.3"   

                               Screen                         CPU   RAM   
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB  \
1                            1440x900        Intel Core i5 1.8GHz   8GB   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU Operating System   
0            128GB SSD  Intel Iris Plus Graphics 640            macOS  \
1  128GB Flash Storage        Intel HD Graphics 6000            macOS   
2            256GB SSD         Intel HD Graphics 620            No OS   
3            512GB SSD            AMD Radeon Pro 455            macOS   
4            256GB SSD  Intel Iris Plus Graphics 650            macOS   

  Operating System Version  Weight        Price  
0                      NaN  1.37kg  11912523.48  
1                      NaN  1.34kg   7993374.48  
2                      NaN  1.86kg   5112900.00  
3                      NaN  1.83kg  22563005.40  
4                      NaN  1.37kg  16037611.20

In [4]:
orde.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Manufacturer              977 non-null    object 
 1   Model Name                977 non-null    object 
 2   Category                  977 non-null    object 
 3   Screen Size               977 non-null    object 
 4   Screen                    977 non-null    object 
 5   CPU                       977 non-null    object 
 6   RAM                       977 non-null    object 
 7    Storage                  977 non-null    object 
 8   GPU                       977 non-null    object 
 9   Operating System          977 non-null    object 
 10  Operating System Version  841 non-null    object 
 11  Weight                    977 non-null    object 
 12  Price                     977 non-null    float64
dtypes: float64(1), object(12)
memory usage: 99.4+ KB


Elimino las filas que considero que no son relevantes o que tienen nulos (y no son relevantes según mi criterio)

In [5]:
pc = orde.drop(['Model Name', 'Screen', 'Operating System', 'Operating System Version'], axis=1)

In [6]:
pc.head()

Manufacturer   Category Screen Size                         CPU   RAM   
0        Apple  Ultrabook       13.3"        Intel Core i5 2.3GHz   8GB  \
1        Apple  Ultrabook       13.3"        Intel Core i5 1.8GHz   8GB   
2           HP   Notebook       15.6"  Intel Core i5 7200U 2.5GHz   8GB   
3        Apple  Ultrabook       15.4"        Intel Core i7 2.7GHz  16GB   
4        Apple  Ultrabook       13.3"        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU  Weight        Price  
0            128GB SSD  Intel Iris Plus Graphics 640  1.37kg  11912523.48  
1  128GB Flash Storage        Intel HD Graphics 6000  1.34kg   7993374.48  
2            256GB SSD         Intel HD Graphics 620  1.86kg   5112900.00  
3            512GB SSD            AMD Radeon Pro 455  1.83kg  22563005.40  
4            256GB SSD  Intel Iris Plus Graphics 650  1.37kg  16037611.20

In [7]:
pc.Manufacturer.unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [8]:
marcas = {'Apple': 5, 'MSI': 4, 'Samsung': 3, 'HP': 2, 'Acer': 2, 'Asus': 2, 'Dell': 2, 'Lenovo': 2, 
          'Chuwi': 0, 'Microsoft': 2, 'Toshiba': 2, 'Huawei': 1, 'Xiaomi': 1, 'Vero': 0, 'Razer': 1,
         'Mediacom': 0, 'Google': 2, 'Fujitsu': 2, 'LG': 2}

In [9]:
pc['Manufacturer'] = pc['Manufacturer'].map(marcas)

In [10]:
pc.head()

Manufacturer   Category Screen Size                         CPU   RAM   
0             5  Ultrabook       13.3"        Intel Core i5 2.3GHz   8GB  \
1             5  Ultrabook       13.3"        Intel Core i5 1.8GHz   8GB   
2             2   Notebook       15.6"  Intel Core i5 7200U 2.5GHz   8GB   
3             5  Ultrabook       15.4"        Intel Core i7 2.7GHz  16GB   
4             5  Ultrabook       13.3"        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU  Weight        Price  
0            128GB SSD  Intel Iris Plus Graphics 640  1.37kg  11912523.48  
1  128GB Flash Storage        Intel HD Graphics 6000  1.34kg   7993374.48  
2            256GB SSD         Intel HD Graphics 620  1.86kg   5112900.00  
3            512GB SSD            AMD Radeon Pro 455  1.83kg  22563005.40  
4            256GB SSD  Intel Iris Plus Graphics 650  1.37kg  16037611.20

In [11]:
pc.Category.unique()

array(['Ultrabook', 'Notebook', 'Netbook', 'Gaming', '2 in 1 Convertible',
       'Workstation'], dtype=object)

In [12]:
category = {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 1, 'Gaming': 6, '2 in 1 Convertible': 2, 'Workstation': 5}

In [13]:
pc['Category'] = pc['Category'].map(category)

In [14]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  977 non-null    int64  
 1   Category      977 non-null    int64  
 2   Screen Size   977 non-null    object 
 3   CPU           977 non-null    object 
 4   RAM           977 non-null    object 
 5    Storage      977 non-null    object 
 6   GPU           977 non-null    object 
 7   Weight        977 non-null    object 
 8   Price         977 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 68.8+ KB


In [15]:
pc.head()

Manufacturer  Category Screen Size                         CPU   RAM   
0             5         4       13.3"        Intel Core i5 2.3GHz   8GB  \
1             5         4       13.3"        Intel Core i5 1.8GHz   8GB   
2             2         3       15.6"  Intel Core i5 7200U 2.5GHz   8GB   
3             5         4       15.4"        Intel Core i7 2.7GHz  16GB   
4             5         4       13.3"        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU  Weight        Price  
0            128GB SSD  Intel Iris Plus Graphics 640  1.37kg  11912523.48  
1  128GB Flash Storage        Intel HD Graphics 6000  1.34kg   7993374.48  
2            256GB SSD         Intel HD Graphics 620  1.86kg   5112900.00  
3            512GB SSD            AMD Radeon Pro 455  1.83kg  22563005.40  
4            256GB SSD  Intel Iris Plus Graphics 650  1.37kg  16037611.20

In [16]:
pc['Screen Size'].unique()

array(['13.3"', '15.6"', '15.4"', '14.0"', '12.0"', '11.6"', '17.3"',
       '10.1"', '13.5"', '12.5"', '13.0"', '18.4"', '13.9"', '12.3"',
       '17.0"', '15.0"', '14.1"', '11.3"'], dtype=object)

In [17]:
pc['Screen Size'] = pc['Screen Size'].str.replace('"', '')

In [18]:
pc['Screen Size'].unique()

array(['13.3', '15.6', '15.4', '14.0', '12.0', '11.6', '17.3', '10.1',
       '13.5', '12.5', '13.0', '18.4', '13.9', '12.3', '17.0', '15.0',
       '14.1', '11.3'], dtype=object)

In [19]:
pc['Screen Size'] = pc['Screen Size'].astype(float)

In [20]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  977 non-null    int64  
 1   Category      977 non-null    int64  
 2   Screen Size   977 non-null    float64
 3   CPU           977 non-null    object 
 4   RAM           977 non-null    object 
 5    Storage      977 non-null    object 
 6   GPU           977 non-null    object 
 7   Weight        977 non-null    object 
 8   Price         977 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 68.8+ KB


In [21]:
pc.head()

Manufacturer  Category  Screen Size                         CPU   RAM   
0             5         4         13.3        Intel Core i5 2.3GHz   8GB  \
1             5         4         13.3        Intel Core i5 1.8GHz   8GB   
2             2         3         15.6  Intel Core i5 7200U 2.5GHz   8GB   
3             5         4         15.4        Intel Core i7 2.7GHz  16GB   
4             5         4         13.3        Intel Core i5 3.1GHz   8GB   

               Storage                           GPU  Weight        Price  
0            128GB SSD  Intel Iris Plus Graphics 640  1.37kg  11912523.48  
1  128GB Flash Storage        Intel HD Graphics 6000  1.34kg   7993374.48  
2            256GB SSD         Intel HD Graphics 620  1.86kg   5112900.00  
3            512GB SSD            AMD Radeon Pro 455  1.83kg  22563005.40  
4            256GB SSD  Intel Iris Plus Graphics 650  1.37kg  16037611.20

In [22]:
pc['CPU'].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Du

In [23]:
cpu_range = {
    'Intel Core i5 2.3GHz': 6,
    'Intel Core i5 1.8GHz': 5,
    'Intel Core i5 7200U 2.5GHz': 6,
    'Intel Core i7 2.7GHz': 8,
    'Intel Core i5 3.1GHz': 7,
    'AMD A9-Series 9420 3GHz': 4,
    'Intel Core i7 2.2GHz': 7,
    'Intel Core i7 8550U 1.8GHz': 9,
    'Intel Core i5 8250U 1.6GHz': 8,
    'Intel Core i3 6006U 2GHz': 5,
    'Intel Core i7 2.8GHz': 8,
    'Intel Core M m3 1.2GHz': 4,
    'Intel Core i7 7500U 2.7GHz': 7,
    'Intel Core i7 2.9GHz': 8,
    'Intel Core i3 7100U 2.4GHz': 6,
    'Intel Atom x5-Z8350 1.44GHz': 3,
    'Intel Core i5 7300HQ 2.5GHz': 7,
    'AMD E-Series E2-9000e 1.5GHz': 3,
    'Intel Core i5 1.6GHz': 6,
    'Intel Core i7 8650U 1.9GHz': 9,
    'Intel Atom x5-Z8300 1.44GHz': 3,
    'AMD E-Series E2-6110 1.5GHz': 3,
    'AMD A6-Series 9220 2.5GHz': 4,
    'Intel Celeron Dual Core N3350 1.1GHz': 1,
    'Intel Core i3 7130U 2.7GHz': 6,
    'Intel Core i7 7700HQ 2.8GHz': 8,
    'Intel Core i5 2.0GHz': 6,
    'AMD Ryzen 1700 3GHz': 7,
    'Intel Pentium Quad Core N4200 1.1GHz': 4,
    'Intel Atom x5-Z8550 1.44GHz': 3,
    'Intel Celeron Dual Core N3060 1.6GHz': 2,
    'Intel Core i5 1.3GHz': 5,
    'AMD FX 9830P 3GHz': 7,
    'Intel Core i7 7560U 2.4GHz': 7,
    'AMD E-Series 6110 1.5GHz': 3,
    'Intel Core i5 6200U 2.3GHz': 6,
    'Intel Core M 6Y75 1.2GHz': 4,
    'Intel Core i5 7500U 2.7GHz': 7,
    'Intel Core i3 6006U 2.2GHz': 5,
    'AMD A6-Series 9220 2.9GHz': 4,
    'Intel Core i7 6920HQ 2.9GHz': 9,
    'Intel Core i5 7Y54 1.2GHz': 6,
    'Intel Core i7 7820HK 2.9GHz': 9,
    'Intel Xeon E3-1505M V6 3GHz': 10,
    'Intel Core i7 6500U 2.5GHz': 8,
    'AMD E-Series 9000e 1.5GHz': 4,
    'AMD A10-Series A10-9620P 2.5GHz': 7,
    'AMD A6-Series A6-9220 2.5GHz': 6,
    'Intel Core i5 2.9GHz': 8,
    'Intel Core i7 6600U 2.6GHz': 8,
    'Intel Core i3 6006U 2.0GHz': 5,
    'Intel Celeron Dual Core 3205U 1.5GHz': 4,
    'Intel Core i7 7820HQ 2.9GHz': 9,
    'AMD A10-Series 9600P 2.4GHz': 7,
    'Intel Core i7 7600U 2.8GHz': 8,
    'AMD A8-Series 7410 2.2GHz': 6,
    'Intel Celeron Dual Core 3855U 1.6GHz': 4,
    'Intel Pentium Quad Core N3710 1.6GHz': 5,
    'AMD A12-Series 9720P 2.7GHz': 7,
    'Intel Core i5 7300U 2.6GHz': 8,
    'AMD A12-Series 9720P 3.6GHz': 9,
    'Intel Celeron Quad Core N3450 1.1GHz': 5,
    'Intel Celeron Dual Core N3060 1.60GHz': 4,
    'Intel Core i5 6440HQ 2.6GHz': 7,
    'Intel Core i7 6820HQ 2.7GHz': 8,
    'AMD Ryzen 1600 3.2GHz': 9,
    'Intel Core i7 7Y75 1.3GHz': 6,
    'Intel Core i5 7440HQ 2.8GHz': 7,
    'Intel Core i7 7660U 2.5GHz': 8,
    'Intel Core i7 7700HQ 2.7GHz': 8,
    'Intel Core M m3-7Y30 2.2GHz': 5,
    'Intel Core i5 7Y57 1.2GHz': 6,
    'Intel Core i7 6700HQ 2.6GHz': 8,
    'Intel Core i3 6100U 2.3GHz': 5,
    'AMD A10-Series 9620P 2.5GHz': 7,
    'AMD E-Series 7110 1.8GHz': 4,
    'Intel Celeron Dual Core N3350 2.0GHz': 4,
    'AMD A9-Series A9-9420 3GHz': 6,
    'Intel Core i7 6820HK 2.7GHz': 8,
    'Intel Core M 7Y30 1.0GHz': 4,
    'Intel Xeon E3-1535M v6 3.1GHz': 9,
    'Intel Celeron Quad Core N3160 1.6GHz': 4,
    'Intel Core i5 6300U 2.4GHz': 7,
    'Intel Core i3 6100U 2.1GHz': 5,
    'AMD E-Series E2-9000 2.2GHz': 5,
    'Intel Celeron Dual Core N3050 1.6GHz': 4,
    'Intel Core M M3-6Y30 0.9GHz': 3,
    'AMD A9-Series 9420 2.9GHz': 6,
    'Intel Core i5 6300HQ 2.3GHz': 7,
    'AMD A6-Series 7310 2GHz': 5,
    'Intel Atom Z8350 1.92GHz': 3,
    'Intel Xeon E3-1535M v5 2.9GHz': 8,
    'Intel Core i5 6260U 1.8GHz': 6,
    'Intel Pentium Dual Core N4200 1.1GHz': 4,
    'Intel Celeron Quad Core N3710 1.6GHz': 4,
    'Intel Core M 1.2GHz': 2,
    'AMD A12-Series 9700P 2.5GHz': 7,
    'Intel Core i7 7500U 2.5GHz': 8,
    'Intel Pentium Dual Core 4405U 2.1GHz': 5,
    'AMD A4-Series 7210 2.2GHz': 5,
    'Intel Core i7 6560U 2.2GHz': 7,
    'Intel Core M m7-6Y75 1.2GHz': 6,
    'AMD FX 8800P 2.1GHz': 6,
    'Intel Core M M7-6Y75 1.2GHz': 5,
    'Intel Core i5 7200U 2.50GHz': 7,
    'Intel Core i5 7200U 2.70GHz': 7
}

In [24]:
pc['CPU'] = pc['CPU'].map(cpu_range)

In [25]:
pc['CPU'].unique()

array([ 6,  5,  8,  7,  4,  9,  3,  1,  2, 10], dtype=int64)

In [26]:
pc['RAM'].unique()

array(['8GB', '16GB', '4GB', '2GB', '12GB', '6GB', '32GB', '24GB'],
      dtype=object)

In [27]:
pc['RAM'] = pc['RAM'].str.replace('GB', '')

In [28]:
pc['RAM'].unique()

array(['8', '16', '4', '2', '12', '6', '32', '24'], dtype=object)

In [29]:
pc['RAM'] = pc['RAM'].astype(int)

In [30]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  977 non-null    int64  
 1   Category      977 non-null    int64  
 2   Screen Size   977 non-null    float64
 3   CPU           977 non-null    int64  
 4   RAM           977 non-null    int32  
 5    Storage      977 non-null    object 
 6   GPU           977 non-null    object 
 7   Weight        977 non-null    object 
 8   Price         977 non-null    float64
dtypes: float64(2), int32(1), int64(3), object(3)
memory usage: 65.0+ KB


In [31]:
pc = pc.rename(columns={' Storage': 'Storage'})

In [32]:
pc['Storage'].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '32GB Flash Storage', '128GB SSD +  1TB HDD',
       '256GB SSD +  256GB SSD', '64GB Flash Storage',
       '256GB SSD +  1TB HDD', '256GB SSD +  2TB HDD', '32GB SSD',
       '2TB HDD', '64GB SSD', '1TB Hybrid', '512GB SSD +  1TB HDD',
       '1TB SSD', '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '1GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid'], dtype=object)

In [33]:
pc['Storage'] = pc['Storage'].str.replace('Storage', '')

In [34]:
pc['Storage'].unique()

array(['128GB SSD', '128GB Flash ', '256GB SSD', '512GB SSD', '500GB HDD',
       '256GB Flash ', '1TB HDD', '32GB Flash ', '128GB SSD +  1TB HDD',
       '256GB SSD +  256GB SSD', '64GB Flash ', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash ',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash  +  1TB HDD', '1GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash ', '128GB HDD',
       '240GB SSD', '8GB SSD', '508GB Hybrid'], dtype=object)

In [35]:
pc[['Storage_size', 'Storage_type']] = pc['Storage'].str.split(' + ', n=1, expand=True)

In [36]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM       Storage   
0             5         4         13.3    6    8     128GB SSD  \
1             5         4         13.3    5    8  128GB Flash    
2             2         3         15.6    6    8     256GB SSD   
3             5         4         15.4    8   16     512GB SSD   
4             5         4         13.3    7    8     256GB SSD   

                            GPU  Weight        Price  Storage_size   
0  Intel Iris Plus Graphics 640  1.37kg  11912523.48     128GB SSD  \
1        Intel HD Graphics 6000  1.34kg   7993374.48  128GB Flash    
2         Intel HD Graphics 620  1.86kg   5112900.00     256GB SSD   
3            AMD Radeon Pro 455  1.83kg  22563005.40     512GB SSD   
4  Intel Iris Plus Graphics 650  1.37kg  16037611.20     256GB SSD   

  Storage_type  
0         None  
1         None  
2         None  
3         None  
4         None

In [37]:
pc = pc.drop('Storage', axis=1)

In [38]:
pc['Storage_size'].unique()

array(['128GB SSD', '128GB Flash ', '256GB SSD', '512GB SSD', '500GB HDD',
       '256GB Flash ', '1TB HDD', '32GB Flash ', '128GB SSD +',
       '256GB SSD +', '64GB Flash ', '32GB SSD', '2TB HDD', '64GB SSD',
       '1TB Hybrid', '512GB SSD +', '1TB SSD', '16GB SSD', '16GB Flash ',
       '64GB Flash', '1GB SSD', '1TB HDD +', '32GB HDD', '1TB SSD +',
       '512GB Flash ', '128GB HDD', '240GB SSD', '8GB SSD',
       '508GB Hybrid'], dtype=object)

In [39]:
pc['Storage_size'] = pc['Storage_size'].str.replace(' +', '')

In [40]:
pc['Storage_size'].unique()

array(['128GB SSD', '128GB Flash ', '256GB SSD', '512GB SSD', '500GB HDD',
       '256GB Flash ', '1TB HDD', '32GB Flash ', '64GB Flash ',
       '32GB SSD', '2TB HDD', '64GB SSD', '1TB Hybrid', '1TB SSD',
       '16GB SSD', '16GB Flash ', '64GB Flash', '1GB SSD', '32GB HDD',
       '512GB Flash ', '128GB HDD', '240GB SSD', '8GB SSD',
       '508GB Hybrid'], dtype=object)

In [41]:
pc['Storage_size'] = pc['Storage_size'].str.replace('GB', '000')

In [42]:
pc['Storage_size'].unique()

array(['128000 SSD', '128000 Flash ', '256000 SSD', '512000 SSD',
       '500000 HDD', '256000 Flash ', '1TB HDD', '32000 Flash ',
       '64000 Flash ', '32000 SSD', '2TB HDD', '64000 SSD', '1TB Hybrid',
       '1TB SSD', '16000 SSD', '16000 Flash ', '64000 Flash', '1000 SSD',
       '32000 HDD', '512000 Flash ', '128000 HDD', '240000 SSD',
       '8000 SSD', '508000 Hybrid'], dtype=object)

In [43]:
pc['Storage_size'] = pc['Storage_size'].str.replace('TB', '000000')

In [44]:
pc['Storage_size'].unique()

array(['128000 SSD', '128000 Flash ', '256000 SSD', '512000 SSD',
       '500000 HDD', '256000 Flash ', '1000000 HDD', '32000 Flash ',
       '64000 Flash ', '32000 SSD', '2000000 HDD', '64000 SSD',
       '1000000 Hybrid', '1000000 SSD', '16000 SSD', '16000 Flash ',
       '64000 Flash', '1000 SSD', '32000 HDD', '512000 Flash ',
       '128000 HDD', '240000 SSD', '8000 SSD', '508000 Hybrid'],
      dtype=object)

In [45]:
pc[['Storage_size1', 'Storage_type1']] = pc['Storage_size'].str.split(' ', n=1, expand=True)

In [46]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    object 
 7   Price          977 non-null    float64
 8   Storage_size   977 non-null    object 
 9   Storage_type   159 non-null    object 
 10  Storage_size1  977 non-null    object 
 11  Storage_type1  977 non-null    object 
dtypes: float64(2), int32(1), int64(3), object(6)
memory usage: 87.9+ KB


In [47]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM   
0             5         4         13.3    6    8  \
1             5         4         13.3    5    8   
2             2         3         15.6    6    8   
3             5         4         15.4    8   16   
4             5         4         13.3    7    8   

                            GPU  Weight        Price   Storage_size   
0  Intel Iris Plus Graphics 640  1.37kg  11912523.48     128000 SSD  \
1        Intel HD Graphics 6000  1.34kg   7993374.48  128000 Flash    
2         Intel HD Graphics 620  1.86kg   5112900.00     256000 SSD   
3            AMD Radeon Pro 455  1.83kg  22563005.40     512000 SSD   
4  Intel Iris Plus Graphics 650  1.37kg  16037611.20     256000 SSD   

  Storage_type Storage_size1 Storage_type1  
0         None        128000           SSD  
1         None        128000        Flash   
2         None        256000           SSD  
3         None        512000           SSD  
4         None        256000           SSD

In [48]:
pc['Storage_size1'] = pc['Storage_size1'].astype(int)

In [49]:
pc = pc.drop('Storage_size', axis=1)

In [50]:
pc['Storage_type'].unique()

array([None, '1TB HDD', '256GB SSD', '2TB HDD', '500GB HDD', '512GB SSD',
       '+  1TB HDD'], dtype=object)

In [51]:
pc['Storage_type'] = pc['Storage_type'].str.replace('+ ', '')

In [52]:
pc['Storage_type'].unique()

array([None, '1TB HDD', '256GB SSD', '2TB HDD', '500GB HDD', '512GB SSD',
       ' 1TB HDD'], dtype=object)

In [53]:
pc['Storage_type'] = pc['Storage_type'].str.replace('GB', '000')
pc['Storage_type'] = pc['Storage_type'].str.replace('TB', '000000')

In [54]:
pc['Storage_type'].unique()

array([None, '1000000 HDD', '256000 SSD', '2000000 HDD', '500000 HDD',
       '512000 SSD', ' 1000000 HDD'], dtype=object)

In [55]:
pc['Storage_type'] = pc['Storage_type'].fillna(0)

In [56]:
pc['Storage_type'].unique()

array([0, '1000000 HDD', '256000 SSD', '2000000 HDD', '500000 HDD',
       '512000 SSD', ' 1000000 HDD'], dtype=object)

In [57]:
pc['Storage_type'] = pc['Storage_type'].str.strip()

In [58]:
pc['Storage_type'].unique()

array([nan, '1000000 HDD', '256000 SSD', '2000000 HDD', '500000 HDD',
       '512000 SSD'], dtype=object)

In [59]:
pc['Storage_type'] = pc['Storage_type'].fillna(0)

In [60]:
pc[['Storage_size2', 'Storage_type2']] = pc['Storage_type'].str.split(' ', n=1, expand=True)

In [61]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM   
0             5         4         13.3    6    8  \
1             5         4         13.3    5    8   
2             2         3         15.6    6    8   
3             5         4         15.4    8   16   
4             5         4         13.3    7    8   

                            GPU  Weight        Price Storage_type   
0  Intel Iris Plus Graphics 640  1.37kg  11912523.48            0  \
1        Intel HD Graphics 6000  1.34kg   7993374.48            0   
2         Intel HD Graphics 620  1.86kg   5112900.00            0   
3            AMD Radeon Pro 455  1.83kg  22563005.40            0   
4  Intel Iris Plus Graphics 650  1.37kg  16037611.20            0   

   Storage_size1 Storage_type1 Storage_size2 Storage_type2  
0         128000           SSD           NaN           NaN  
1         128000        Flash            NaN           NaN  
2         256000           SSD           NaN           NaN  
3         512000           SSD           NaN           NaN  
4         256000           SSD           NaN           NaN

In [62]:
pc['Storage_type2'] = pc['Storage_type2'].fillna(0)

In [63]:
pc['Storage_type2'].unique()

array([0, 'HDD', 'SSD'], dtype=object)

In [64]:
pc['Storage_size2'].unique()

array([nan, '1000000', '256000', '2000000', '500000', '512000'],
      dtype=object)

In [65]:
pc['Storage_size2'] = pc['Storage_size2'].fillna(0)

In [66]:
pc['Storage_size2'] = pc['Storage_size2'].astype(int)

In [67]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    object 
 7   Price          977 non-null    float64
 8   Storage_type   977 non-null    object 
 9   Storage_size1  977 non-null    int32  
 10  Storage_type1  977 non-null    object 
 11  Storage_size2  977 non-null    int32  
 12  Storage_type2  977 non-null    object 
dtypes: float64(2), int32(3), int64(3), object(5)
memory usage: 87.9+ KB


In [68]:
pc = pc.drop('Storage_type', axis=1)

In [69]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    object 
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    object 
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    object 
dtypes: float64(2), int32(3), int64(3), object(4)
memory usage: 80.3+ KB


In [70]:
pc['Storage_type1'].unique()

array(['SSD', 'Flash ', 'HDD', 'Hybrid', 'Flash'], dtype=object)

In [71]:
pc['Storage_type1'] = pc['Storage_type1'].str.strip()

In [72]:
pc['Storage_type1'].unique()

array(['SSD', 'Flash', 'HDD', 'Hybrid'], dtype=object)

In [73]:
pesos_discos = {
    'SSD': 4,
    'Hybrid': 3,
    'Flash': 2,
    'HDD': 1,
    'None': 0
}

In [74]:
pc['Storage_type1'] = pc['Storage_type1'].map(pesos_discos)

In [75]:
pc['Storage_type2'] = pc['Storage_type2'].map(pesos_discos)

In [76]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    object 
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  159 non-null    float64
dtypes: float64(3), int32(3), int64(4), object(2)
memory usage: 80.3+ KB


In [77]:
pc['Storage_type1'].unique()

array([4, 2, 1, 3], dtype=int64)

In [78]:
pc['Storage_type2'].unique()

array([nan,  1.,  4.])

In [79]:
pc['Storage_type2'] = pc['Storage_type2'].fillna(0)

In [80]:
pc['Storage_type2'].unique()

array([0., 1., 4.])

In [81]:
pc['Storage_type2'] = pc['Storage_type2'].astype(int)

In [82]:
pc['Storage_type2'].unique()

array([0, 1, 4])

In [83]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    object 
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    int32  
dtypes: float64(2), int32(4), int64(4), object(2)
memory usage: 76.5+ KB


In [84]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM   
0             5         4         13.3    6    8  \
1             5         4         13.3    5    8   
2             2         3         15.6    6    8   
3             5         4         15.4    8   16   
4             5         4         13.3    7    8   

                            GPU  Weight        Price  Storage_size1   
0  Intel Iris Plus Graphics 640  1.37kg  11912523.48         128000  \
1        Intel HD Graphics 6000  1.34kg   7993374.48         128000   
2         Intel HD Graphics 620  1.86kg   5112900.00         256000   
3            AMD Radeon Pro 455  1.83kg  22563005.40         512000   
4  Intel Iris Plus Graphics 650  1.37kg  16037611.20         256000   

   Storage_type1  Storage_size2  Storage_type2  
0              4              0              0  
1              2              0              0  
2              4              0              0  
3              4              0              0  
4              4              0              0

In [85]:
pc['Weight'].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', '0.98kg', '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '0.69kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg',
       '1.4kg', '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg',
       '1.63kg', '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg',
       '2.62kg', '1.38kg', '1.58kg', '1.85kg', '1.23kg', '1.26kg',
       '2.16kg', '2.36kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg',
       '2.9kg', '2.56kg', '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg',
       '1.05kg', '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg',
       '1.12kg', '1.42kg', '3.49kg', '3.35kg', '2.23kg', '4.42kg',
       '2.69kg', '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg',
       '1.41kg', '4.14kg', '2.18kg', '2.24kg', '2.67kg', '2.14kg',
       '1.

In [86]:
pc['Weight'] = pc['Weight'].str.strip()

In [87]:
pc['Weight'] = pc['Weight'].str.replace('kg', '')

In [88]:
pc['Weight'].unique()

array(['1.37', '1.34', '1.86', '1.83', '2.1', '2.04', '1.3', '1.6', '2.2',
       '0.92', '1.22', '0.98', '2.5', '1.62', '1.91', '2.3', '1.35',
       '1.88', '1.89', '1.65', '2.71', '1.2', '1.44', '2.8', '2', '2.65',
       '2.77', '3.2', '0.69', '1.49', '2.4', '2.13', '2.43', '1.7', '1.4',
       '1.8', '1.9', '3', '1.252', '2.7', '2.02', '1.63', '1.96', '1.21',
       '2.45', '1.25', '1.5', '2.62', '1.38', '1.58', '1.85', '1.23',
       '1.26', '2.16', '2.36', '2.05', '1.32', '1.75', '0.97', '2.9',
       '2.56', '1.48', '1.74', '1.1', '1.56', '2.03', '1.05', '4.4',
       '1.90', '1.29', '2.0', '1.95', '2.06', '1.12', '1.42', '3.49',
       '3.35', '2.23', '4.42', '2.69', '2.37', '4.7', '3.6', '2.08',
       '4.3', '1.68', '1.41', '4.14', '2.18', '2.24', '2.67', '2.14',
       '1.36', '2.25', '2.15', '2.19', '2.54', '3.42', '1.28', '2.33',
       '1.45', '2.79', '1.84', '2.6', '2.26', '3.25', '1.59', '1.13',
       '1.78', '1.10', '1.15', '1.27', '1.43', '2.31', '1.16', '1.64',
   

In [89]:
pc['Weight'] = pc['Weight'].astype(float)

In [90]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    object 
 6   Weight         977 non-null    float64
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    int32  
dtypes: float64(3), int32(4), int64(4), object(1)
memory usage: 76.5+ KB


In [91]:
pc['GPU'].unique()

array(['Intel Iris Plus Graphics 640', 'Intel HD Graphics 6000',
       'Intel HD Graphics 620', 'AMD Radeon Pro 455',
       'Intel Iris Plus Graphics 650', 'AMD Radeon R5',
       'Intel Iris Pro Graphics', 'Nvidia GeForce MX150',
       'Intel UHD Graphics 620', 'Intel HD Graphics 520',
       'AMD Radeon Pro 555', 'AMD Radeon R5 M430',
       'Intel HD Graphics 615', 'AMD Radeon Pro 560',
       'Nvidia GeForce 940MX', 'Intel HD Graphics 400',
       'Nvidia GeForce GTX 1050', 'AMD Radeon R2', 'AMD Radeon 530',
       'Nvidia GeForce 930MX', 'Intel HD Graphics',
       'Intel HD Graphics 500', 'Nvidia GeForce 930MX ',
       'Nvidia GeForce GTX 1060', 'Nvidia GeForce 150MX',
       'Intel Iris Graphics 540', 'AMD Radeon RX 580',
       'Nvidia GeForce 920MX', 'AMD Radeon R4 Graphics', 'AMD Radeon 520',
       'Nvidia GeForce GTX 1070', 'Nvidia GeForce GTX 1050 Ti',
       'Nvidia GeForce MX130', 'AMD R4 Graphics',
       'Nvidia GeForce GTX 940MX', 'AMD Radeon RX 560',
       'Nvid

In [95]:
pesos_grafica = {
    'Intel HD Graphics 6000': 3,
    'Intel HD Graphics 620': 3,
    'AMD Radeon Pro 455': 4,
    'Intel Iris Plus Graphics 650': 4,
    'AMD Radeon R5': 3,
    'Intel Iris Pro Graphics': 4,
    'Nvidia GeForce MX150': 4,
    'Intel UHD Graphics 620': 3,
    'Intel HD Graphics 520': 3,
    'AMD Radeon Pro 555': 4,
    'AMD Radeon R5 M430': 3,
    'Intel HD Graphics 615': 3,
    'AMD Radeon Pro 560': 4,
    'Nvidia GeForce 940MX': 3,
    'Intel HD Graphics 400': 2,
    'Nvidia GeForce GTX 1050': 4,
    'AMD Radeon R2': 2,
    'AMD Radeon 530': 3,
    'Nvidia GeForce 930MX': 3,
    'Intel HD Graphics': 2,
    'Intel HD Graphics 500': 3,
    'Nvidia GeForce 930MX ': 3,
    'Nvidia GeForce GTX 1060': 5,
    'Nvidia GeForce 150MX': 3,
    'Intel Iris Graphics 540': 4,
    'AMD Radeon RX 580': 5,
    'Nvidia GeForce 920MX': 3,
    'AMD Radeon R4 Graphics': 2,
    'AMD Radeon 520': 3,
    'Nvidia GeForce GTX 1070': 5,
    'Nvidia GeForce GTX 1050 Ti': 4,
    'Nvidia GeForce MX130': 3,
    'AMD R4 Graphics': 2,
    'Nvidia GeForce GTX 940MX': 3,
    'AMD Radeon RX 560': 4,
    'Nvidia GeForce 920M': 2,
    'AMD Radeon R7 M445': 3,
    'AMD Radeon RX 550': 4,
    'Nvidia GeForce GTX 1050M': 4,
    'Intel HD Graphics 515': 3,
    'AMD Radeon R5 M420': 3,
    'Intel HD Graphics 505': 3,
    'Nvidia GTX 980 SLI': 5,
    'AMD R17M-M1-70': 4,
    'Nvidia GeForce GTX 1080': 5,
    'Nvidia Quadro M1200': 4,
    'Nvidia GeForce 920MX ': 2,
    'Nvidia GeForce GTX 950M': 4,
    'AMD FirePro W4190M ': 3,
    'Nvidia GeForce GTX 980M': 5,
    'Intel Iris Graphics 550': 4,
    'Nvidia GeForce 930M': 3,
    'Intel HD Graphics 630': 3,
    'AMD Radeon R5 430': 3,
    'Nvidia GeForce GTX 940M': 4,
    'Intel HD Graphics 510': 3,
    'Intel HD Graphics 405': 2,
    'AMD Radeon RX 540': 4,
    'Nvidia GeForce GT 940MX': 3,
    'AMD FirePro W5130M': 3,
    'Nvidia Quadro M2200M': 4,
    'AMD Radeon R4': 2,
    'Nvidia Quadro M620': 4,
    'AMD Radeon R7 M460': 3,
    'Intel HD Graphics 530': 4,
    'Nvidia GeForce GTX 965M': 4,
    'Nvidia GeForce GTX1080': 5,
    'Nvidia GeForce GTX1050 Ti': 4,
    'Nvidia GeForce GTX 960M': 4,
    'AMD Radeon R2 Graphics': 2,
    'Nvidia Quadro M620M': 4,
    'Nvidia GeForce GTX 970M': 4,
    'Nvidia GeForce GTX 960<U+039C>': 4,
    'Intel Graphics 620': 3,
    'Nvidia GeForce GTX 960': 4,
    'AMD Radeon R5 520': 3,
    'AMD Radeon R7 M440': 3,
    'AMD Radeon R7': 3,
    'Nvidia Quadro M520M': 4,
    'Nvidia Quadro M2200': 4,
    'Nvidia Quadro M2000M': 4,
    'Intel HD Graphics 540': 3,
    'Nvidia Quadro M1000M': 4,
    'AMD Radeon 540': 3,
    'Nvidia GeForce GTX 1070M': 5,
    'Nvidia GeForce GTX1060': 5,
    'Intel HD Graphics 5300': 2,
    'AMD Radeon R5 M420X': 3,
    'AMD Radeon R7 Graphics': 3,
    'Nvidia GeForce 920': 2,
    'Nvidia GeForce 940M': 3,
    'Nvidia GeForce GTX 930MX': 3,
    'AMD Radeon R7 M465': 3,
    'AMD Radeon R3': 2,
    'Nvidia GeForce GTX 1050Ti': 4,
    'AMD Radeon R7 M365X': 3,
    'AMD Radeon R9 M385': 4
}

In [93]:
pc['GPU'] = pc['GPU'].str.strip()

In [96]:
pc['GPU'] = pc['GPU'].map(pesos_grafica)

In [97]:
pc['GPU'].unique()

array([nan,  3.,  4.,  2.,  5.])

In [98]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            968 non-null    float64
 6   Weight         977 non-null    float64
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    int32  
dtypes: float64(4), int32(4), int64(4)
memory usage: 76.5 KB


In [99]:
pc['GPU'] = pc['GPU'].fillna(0)

In [100]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    float64
 6   Weight         977 non-null    float64
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    int32  
dtypes: float64(4), int32(4), int64(4)
memory usage: 76.5 KB


In [101]:
pc['GPU'] = pc['GPU'].astype(int)

In [102]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   977 non-null    int64  
 1   Category       977 non-null    int64  
 2   Screen Size    977 non-null    float64
 3   CPU            977 non-null    int64  
 4   RAM            977 non-null    int32  
 5   GPU            977 non-null    int32  
 6   Weight         977 non-null    float64
 7   Price          977 non-null    float64
 8   Storage_size1  977 non-null    int32  
 9   Storage_type1  977 non-null    int64  
 10  Storage_size2  977 non-null    int32  
 11  Storage_type2  977 non-null    int32  
dtypes: float64(3), int32(5), int64(4)
memory usage: 72.6 KB


In [103]:
pc.to_csv('pc.csv', index=False)