In [1]:
import pandas as pd
import numpy as np

In [3]:
orde = pd.read_csv('../Proyecto_Kaggle/data/test.csv')

In [3]:
orde.head()

Manufacturer                         Model Name            Category   
0           HP  15-bs053od (i7-7500U/6GB/1TB/W10)            Notebook  \
1         Asus                   Rog GL753VE-DS74              Gaming   
2         Dell                      Inspiron 7579  2 in 1 Convertible   
3      Toshiba                  Portege Z30-C-1CV            Notebook   
4       Lenovo                  IdeaPad 320-15ABR            Notebook   

  Screen Size                                     Screen   
0       15.6"                                   1366x768  \
1       17.3"                          Full HD 1920x1080   
2       15.6"  IPS Panel Full HD / Touchscreen 1920x1080   
3       13.3"                          Full HD 1920x1080   
4       15.6"                          Full HD 1920x1080   

                           CPU   RAM               Storage   
0   Intel Core i7 7500U 2.7GHz   6GB               1TB HDD  \
1  Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD   
2   Intel Core i7 7500U 2.7GHz  12GB             512GB SSD   
3   Intel Core i5 6200U 2.3GHz   4GB             128GB SSD   
4  AMD A12-Series 9720P 3.6GHz   6GB             256GB SSD   

                          GPU Operating System Operating System Version   
0       Intel HD Graphics 620          Windows                       10  \
1  Nvidia GeForce GTX 1050 Ti          Windows                       10   
2       Intel HD Graphics 620          Windows                       10   
3       Intel HD Graphics 520          Windows                        7   
4              AMD Radeon 530          Windows                       10   

   Weight  
0  2.04kg  
1  2.99kg  
2  2.19kg  
3   1.2kg  
4   2.2kg

In [4]:
orde.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Manufacturer              325 non-null    object
 1   Model Name                325 non-null    object
 2   Category                  325 non-null    object
 3   Screen Size               325 non-null    object
 4   Screen                    325 non-null    object
 5   CPU                       325 non-null    object
 6   RAM                       325 non-null    object
 7    Storage                  325 non-null    object
 8   GPU                       325 non-null    object
 9   Operating System          325 non-null    object
 10  Operating System Version  291 non-null    object
 11  Weight                    325 non-null    object
dtypes: object(12)
memory usage: 30.6+ KB


Elimino las filas que considero que no son relevantes o que tienen nulos (y no son relevantes según mi criterio)

In [5]:
pc = orde.drop(['Model Name', 'Screen', 'Operating System', 'Operating System Version'], axis=1)

In [6]:
pc.head()

Manufacturer            Category Screen Size                          CPU   
0           HP            Notebook       15.6"   Intel Core i7 7500U 2.7GHz  \
1         Asus              Gaming       17.3"  Intel Core i7 7700HQ 2.8GHz   
2         Dell  2 in 1 Convertible       15.6"   Intel Core i7 7500U 2.7GHz   
3      Toshiba            Notebook       13.3"   Intel Core i5 6200U 2.3GHz   
4       Lenovo            Notebook       15.6"  AMD A12-Series 9720P 3.6GHz   

    RAM               Storage                         GPU  Weight  
0   6GB               1TB HDD       Intel HD Graphics 620  2.04kg  
1  16GB  256GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  2.99kg  
2  12GB             512GB SSD       Intel HD Graphics 620  2.19kg  
3   4GB             128GB SSD       Intel HD Graphics 520   1.2kg  
4   6GB             256GB SSD              AMD Radeon 530   2.2kg

In [7]:
pc.Manufacturer.unique()

array(['HP', 'Asus', 'Dell', 'Toshiba', 'Lenovo', 'Fujitsu', 'Acer',
       'MSI', 'Vero', 'Apple', 'Razer', 'Samsung'], dtype=object)

In [8]:
marcas = {'Apple': 5, 'MSI': 4, 'Samsung': 3, 'HP': 2, 'Acer': 2, 'Asus': 2, 'Dell': 2, 'Lenovo': 2, 
          'Chuwi': 0, 'Microsoft': 2, 'Toshiba': 2, 'Huawei': 1, 'Xiaomi': 1, 'Vero': 0, 'Razer': 1,
         'Mediacom': 0, 'Google': 2, 'Fujitsu': 2, 'LG': 2}

In [9]:
pc['Manufacturer'] = pc['Manufacturer'].map(marcas)

In [10]:
pc.head()

Manufacturer            Category Screen Size                          CPU   
0             2            Notebook       15.6"   Intel Core i7 7500U 2.7GHz  \
1             2              Gaming       17.3"  Intel Core i7 7700HQ 2.8GHz   
2             2  2 in 1 Convertible       15.6"   Intel Core i7 7500U 2.7GHz   
3             2            Notebook       13.3"   Intel Core i5 6200U 2.3GHz   
4             2            Notebook       15.6"  AMD A12-Series 9720P 3.6GHz   

    RAM               Storage                         GPU  Weight  
0   6GB               1TB HDD       Intel HD Graphics 620  2.04kg  
1  16GB  256GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  2.99kg  
2  12GB             512GB SSD       Intel HD Graphics 620  2.19kg  
3   4GB             128GB SSD       Intel HD Graphics 520   1.2kg  
4   6GB             256GB SSD              AMD Radeon 530   2.2kg

In [11]:
pc.Category.unique()

array(['Notebook', 'Gaming', '2 in 1 Convertible', 'Netbook', 'Ultrabook',
       'Workstation'], dtype=object)

In [12]:
category = {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 1, 'Gaming': 6, '2 in 1 Convertible': 2, 'Workstation': 5}

In [13]:
pc['Category'] = pc['Category'].map(category)

In [14]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Manufacturer  325 non-null    int64 
 1   Category      325 non-null    int64 
 2   Screen Size   325 non-null    object
 3   CPU           325 non-null    object
 4   RAM           325 non-null    object
 5    Storage      325 non-null    object
 6   GPU           325 non-null    object
 7   Weight        325 non-null    object
dtypes: int64(2), object(6)
memory usage: 20.4+ KB


In [15]:
pc.head()

Manufacturer  Category Screen Size                          CPU   RAM   
0             2         3       15.6"   Intel Core i7 7500U 2.7GHz   6GB  \
1             2         6       17.3"  Intel Core i7 7700HQ 2.8GHz  16GB   
2             2         2       15.6"   Intel Core i7 7500U 2.7GHz  12GB   
3             2         3       13.3"   Intel Core i5 6200U 2.3GHz   4GB   
4             2         3       15.6"  AMD A12-Series 9720P 3.6GHz   6GB   

                Storage                         GPU  Weight  
0               1TB HDD       Intel HD Graphics 620  2.04kg  
1  256GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  2.99kg  
2             512GB SSD       Intel HD Graphics 620  2.19kg  
3             128GB SSD       Intel HD Graphics 520   1.2kg  
4             256GB SSD              AMD Radeon 530   2.2kg

In [16]:
pc['Screen Size'].unique()

array(['15.6"', '17.3"', '13.3"', '14.0"', '12.5"', '11.6"', '12.0"',
       '10.1"', '12.3"', '15.0"'], dtype=object)

In [17]:
pc['Screen Size'] = pc['Screen Size'].str.replace('"', '')

In [18]:
pc['Screen Size'].unique()

array(['15.6', '17.3', '13.3', '14.0', '12.5', '11.6', '12.0', '10.1',
       '12.3', '15.0'], dtype=object)

In [19]:
pc['Screen Size'] = pc['Screen Size'].astype(float)

In [20]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  325 non-null    int64  
 1   Category      325 non-null    int64  
 2   Screen Size   325 non-null    float64
 3   CPU           325 non-null    object 
 4   RAM           325 non-null    object 
 5    Storage      325 non-null    object 
 6   GPU           325 non-null    object 
 7   Weight        325 non-null    object 
dtypes: float64(1), int64(2), object(5)
memory usage: 20.4+ KB


In [21]:
pc.head()

Manufacturer  Category  Screen Size                          CPU   RAM   
0             2         3         15.6   Intel Core i7 7500U 2.7GHz   6GB  \
1             2         6         17.3  Intel Core i7 7700HQ 2.8GHz  16GB   
2             2         2         15.6   Intel Core i7 7500U 2.7GHz  12GB   
3             2         3         13.3   Intel Core i5 6200U 2.3GHz   4GB   
4             2         3         15.6  AMD A12-Series 9720P 3.6GHz   6GB   

                Storage                         GPU  Weight  
0               1TB HDD       Intel HD Graphics 620  2.04kg  
1  256GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  2.99kg  
2             512GB SSD       Intel HD Graphics 620  2.19kg  
3             128GB SSD       Intel HD Graphics 520   1.2kg  
4             256GB SSD              AMD Radeon 530   2.2kg

In [22]:
pc['CPU'].unique()

array(['Intel Core i7 7500U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 6200U 2.3GHz', 'AMD A12-Series 9720P 3.6GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core M 6Y75 1.2GHz',
       'Intel Core i3 6006U 2GHz', 'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Core i5 6300U 2.4GHz',
       'Intel Core i7 6600U 2.6GHz', 'Intel Core i5 7300HQ 2.5GHz',
       'Intel Core i7 6500U 2.5GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'Intel Core i3 6100U 2.3GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Atom X5-Z8350 1.44GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core i7 6700HQ 2.6GHz',
       'Intel Celeron Dual Core N3060 1.6GHz',
       'Intel Core i5 7200U 2.7GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Core M 1.1GHz', 'Intel Core i5 6300HQ 2.3GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz

In [23]:
cpu_range = {
    'Intel Core i5 2.3GHz': 6,
    'Intel Core i5 1.8GHz': 5,
    'Intel Core i5 7200U 2.5GHz': 6,
    'Intel Core i7 2.7GHz': 8,
    'Intel Core i5 3.1GHz': 7,
    'AMD A9-Series 9420 3GHz': 4,
    'Intel Core i7 2.2GHz': 7,
    'Intel Core i7 8550U 1.8GHz': 9,
    'Intel Core i5 8250U 1.6GHz': 8,
    'Intel Core i3 6006U 2GHz': 5,
    'Intel Core i7 2.8GHz': 8,
    'Intel Core M m3 1.2GHz': 4,
    'Intel Core i7 7500U 2.7GHz': 7,
    'Intel Core i7 2.9GHz': 8,
    'Intel Core i3 7100U 2.4GHz': 6,
    'Intel Atom x5-Z8350 1.44GHz': 3,
    'Intel Core i5 7300HQ 2.5GHz': 7,
    'AMD E-Series E2-9000e 1.5GHz': 3,
    'Intel Core i5 1.6GHz': 6,
    'Intel Core i7 8650U 1.9GHz': 9,
    'Intel Atom x5-Z8300 1.44GHz': 3,
    'AMD E-Series E2-6110 1.5GHz': 3,
    'AMD A6-Series 9220 2.5GHz': 4,
    'Intel Celeron Dual Core N3350 1.1GHz': 1,
    'Intel Core i3 7130U 2.7GHz': 6,
    'Intel Core i7 7700HQ 2.8GHz': 8,
    'Intel Core i5 2.0GHz': 6,
    'AMD Ryzen 1700 3GHz': 7,
    'Intel Pentium Quad Core N4200 1.1GHz': 4,
    'Intel Atom x5-Z8550 1.44GHz': 3,
    'Intel Celeron Dual Core N3060 1.6GHz': 2,
    'Intel Core i5 1.3GHz': 5,
    'AMD FX 9830P 3GHz': 7,
    'Intel Core i7 7560U 2.4GHz': 7,
    'AMD E-Series 6110 1.5GHz': 3,
    'Intel Core i5 6200U 2.3GHz': 6,
    'Intel Core M 6Y75 1.2GHz': 4,
    'Intel Core i5 7500U 2.7GHz': 7,
    'Intel Core i3 6006U 2.2GHz': 5,
    'AMD A6-Series 9220 2.9GHz': 4,
    'Intel Core i7 6920HQ 2.9GHz': 9,
    'Intel Core i5 7Y54 1.2GHz': 6,
    'Intel Core i7 7820HK 2.9GHz': 9,
    'Intel Xeon E3-1505M V6 3GHz': 10,
    'Intel Core i7 6500U 2.5GHz': 8,
    'AMD E-Series 9000e 1.5GHz': 4,
    'AMD A10-Series A10-9620P 2.5GHz': 7,
    'AMD A6-Series A6-9220 2.5GHz': 6,
    'Intel Core i5 2.9GHz': 8,
    'Intel Core i7 6600U 2.6GHz': 8,
    'Intel Core i3 6006U 2.0GHz': 5,
    'Intel Celeron Dual Core 3205U 1.5GHz': 4,
    'Intel Core i7 7820HQ 2.9GHz': 9,
    'AMD A10-Series 9600P 2.4GHz': 7,
    'Intel Core i7 7600U 2.8GHz': 8,
    'AMD A8-Series 7410 2.2GHz': 6,
    'Intel Celeron Dual Core 3855U 1.6GHz': 4,
    'Intel Pentium Quad Core N3710 1.6GHz': 5,
    'AMD A12-Series 9720P 2.7GHz': 7,
    'Intel Core i5 7300U 2.6GHz': 8,
    'AMD A12-Series 9720P 3.6GHz': 9,
    'Intel Celeron Quad Core N3450 1.1GHz': 5,
    'Intel Celeron Dual Core N3060 1.60GHz': 4,
    'Intel Core i5 6440HQ 2.6GHz': 7,
    'Intel Core i7 6820HQ 2.7GHz': 8,
    'AMD Ryzen 1600 3.2GHz': 9,
    'Intel Core i7 7Y75 1.3GHz': 6,
    'Intel Core i5 7440HQ 2.8GHz': 7,
    'Intel Core i7 7660U 2.5GHz': 8,
    'Intel Core i7 7700HQ 2.7GHz': 8,
    'Intel Core M m3-7Y30 2.2GHz': 5,
    'Intel Core i5 7Y57 1.2GHz': 6,
    'Intel Core i7 6700HQ 2.6GHz': 8,
    'Intel Core i3 6100U 2.3GHz': 5,
    'AMD A10-Series 9620P 2.5GHz': 7,
    'AMD E-Series 7110 1.8GHz': 4,
    'Intel Celeron Dual Core N3350 2.0GHz': 4,
    'AMD A9-Series A9-9420 3GHz': 6,
    'Intel Core i7 6820HK 2.7GHz': 8,
    'Intel Core M 7Y30 1.0GHz': 4,
    'Intel Xeon E3-1535M v6 3.1GHz': 9,
    'Intel Celeron Quad Core N3160 1.6GHz': 4,
    'Intel Core i5 6300U 2.4GHz': 7,
    'Intel Core i3 6100U 2.1GHz': 5,
    'AMD E-Series E2-9000 2.2GHz': 5,
    'Intel Celeron Dual Core N3050 1.6GHz': 4,
    'Intel Core M M3-6Y30 0.9GHz': 3,
    'AMD A9-Series 9420 2.9GHz': 6,
    'Intel Core i5 6300HQ 2.3GHz': 7,
    'AMD A6-Series 7310 2GHz': 5,
    'Intel Atom Z8350 1.92GHz': 3,
    'Intel Xeon E3-1535M v5 2.9GHz': 8,
    'Intel Core i5 6260U 1.8GHz': 6,
    'Intel Pentium Dual Core N4200 1.1GHz': 4,
    'Intel Celeron Quad Core N3710 1.6GHz': 4,
    'Intel Core M 1.2GHz': 2,
    'AMD A12-Series 9700P 2.5GHz': 7,
    'Intel Core i7 7500U 2.5GHz': 8,
    'Intel Pentium Dual Core 4405U 2.1GHz': 5,
    'AMD A4-Series 7210 2.2GHz': 5,
    'Intel Core i7 6560U 2.2GHz': 7,
    'Intel Core M m7-6Y75 1.2GHz': 6,
    'AMD FX 8800P 2.1GHz': 6,
    'Intel Core M M7-6Y75 1.2GHz': 5,
    'Intel Core i5 7200U 2.50GHz': 7,
    'Intel Core i5 7200U 2.70GHz': 7
}

In [24]:
pc['CPU'] = pc['CPU'].map(cpu_range)

In [25]:
pc['CPU'].unique()

array([ 7.,  8.,  6.,  9.,  4.,  5.,  1., nan,  2.,  3.])

In [27]:
pc['CPU'] = pc['CPU'].fillna(0)

In [28]:
pc['CPU'] = pc['CPU'].astype(int)

In [29]:
pc['RAM'].unique()

array(['6GB', '16GB', '12GB', '4GB', '8GB', '2GB', '64GB', '32GB'],
      dtype=object)

In [30]:
pc['RAM'] = pc['RAM'].str.replace('GB', '')

In [31]:
pc['RAM'].unique()

array(['6', '16', '12', '4', '8', '2', '64', '32'], dtype=object)

In [32]:
pc['RAM'] = pc['RAM'].astype(int)

In [33]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Manufacturer  325 non-null    int64  
 1   Category      325 non-null    int64  
 2   Screen Size   325 non-null    float64
 3   CPU           325 non-null    int32  
 4   RAM           325 non-null    int32  
 5    Storage      325 non-null    object 
 6   GPU           325 non-null    object 
 7   Weight        325 non-null    object 
dtypes: float64(1), int32(2), int64(2), object(3)
memory usage: 17.9+ KB


In [34]:
pc = pc.rename(columns={' Storage': 'Storage'})

In [35]:
pc['Storage'].unique()

array(['1TB HDD', '256GB SSD +  1TB HDD', '512GB SSD', '128GB SSD',
       '256GB SSD', '500GB HDD', '128GB SSD +  1TB HDD', '1TB Hybrid',
       '32GB Flash Storage', '256GB SSD +  500GB HDD',
       '16GB Flash Storage', '1TB SSD', '2TB HDD', '256GB Flash Storage',
       '512GB SSD +  1TB Hybrid', '64GB Flash Storage', '1GB SSD',
       '16GB SSD', '256GB SSD +  1TB Hybrid', '512GB SSD +  1TB HDD',
       '512GB Flash Storage', '32GB SSD'], dtype=object)

In [36]:
pc['Storage'] = pc['Storage'].str.replace('Storage', '')

In [37]:
pc['Storage'].unique()

array(['1TB HDD', '256GB SSD +  1TB HDD', '512GB SSD', '128GB SSD',
       '256GB SSD', '500GB HDD', '128GB SSD +  1TB HDD', '1TB Hybrid',
       '32GB Flash ', '256GB SSD +  500GB HDD', '16GB Flash ', '1TB SSD',
       '2TB HDD', '256GB Flash ', '512GB SSD +  1TB Hybrid',
       '64GB Flash ', '1GB SSD', '16GB SSD', '256GB SSD +  1TB Hybrid',
       '512GB SSD +  1TB HDD', '512GB Flash ', '32GB SSD'], dtype=object)

In [38]:
pc[['Storage_size', 'Storage_type']] = pc['Storage'].str.split(' + ', n=1, expand=True)

In [39]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM               Storage   
0             2         3         15.6    7    6               1TB HDD  \
1             2         6         17.3    8   16  256GB SSD +  1TB HDD   
2             2         2         15.6    7   12             512GB SSD   
3             2         3         13.3    6    4             128GB SSD   
4             2         3         15.6    9    6             256GB SSD   

                          GPU  Weight Storage_size Storage_type  
0       Intel HD Graphics 620  2.04kg      1TB HDD         None  
1  Nvidia GeForce GTX 1050 Ti  2.99kg  256GB SSD +      1TB HDD  
2       Intel HD Graphics 620  2.19kg    512GB SSD         None  
3       Intel HD Graphics 520   1.2kg    128GB SSD         None  
4              AMD Radeon 530   2.2kg    256GB SSD         None

In [40]:
pc = pc.drop('Storage', axis=1)

In [41]:
pc['Storage_size'].unique()

array(['1TB HDD', '256GB SSD +', '512GB SSD', '128GB SSD', '256GB SSD',
       '500GB HDD', '128GB SSD +', '1TB Hybrid', '32GB Flash ',
       '16GB Flash ', '1TB SSD', '2TB HDD', '256GB Flash ', '512GB SSD +',
       '64GB Flash ', '1GB SSD', '16GB SSD', '512GB Flash ', '32GB SSD'],
      dtype=object)

In [42]:
pc['Storage_size'] = pc['Storage_size'].str.replace(' +', '')

In [43]:
pc['Storage_size'].unique()

array(['1TB HDD', '256GB SSD', '512GB SSD', '128GB SSD', '500GB HDD',
       '1TB Hybrid', '32GB Flash ', '16GB Flash ', '1TB SSD', '2TB HDD',
       '256GB Flash ', '64GB Flash ', '1GB SSD', '16GB SSD',
       '512GB Flash ', '32GB SSD'], dtype=object)

In [44]:
pc['Storage_size'] = pc['Storage_size'].str.replace('GB', '000')

In [45]:
pc['Storage_size'].unique()

array(['1TB HDD', '256000 SSD', '512000 SSD', '128000 SSD', '500000 HDD',
       '1TB Hybrid', '32000 Flash ', '16000 Flash ', '1TB SSD', '2TB HDD',
       '256000 Flash ', '64000 Flash ', '1000 SSD', '16000 SSD',
       '512000 Flash ', '32000 SSD'], dtype=object)

In [46]:
pc['Storage_size'] = pc['Storage_size'].str.replace('TB', '000000')

In [47]:
pc['Storage_size'].unique()

array(['1000000 HDD', '256000 SSD', '512000 SSD', '128000 SSD',
       '500000 HDD', '1000000 Hybrid', '32000 Flash ', '16000 Flash ',
       '1000000 SSD', '2000000 HDD', '256000 Flash ', '64000 Flash ',
       '1000 SSD', '16000 SSD', '512000 Flash ', '32000 SSD'],
      dtype=object)

In [48]:
pc[['Storage_size1', 'Storage_type1']] = pc['Storage_size'].str.split(' ', n=1, expand=True)

In [49]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    object 
 7   Storage_size   325 non-null    object 
 8   Storage_type   48 non-null     object 
 9   Storage_size1  325 non-null    object 
 10  Storage_type1  325 non-null    object 
dtypes: float64(1), int32(2), int64(2), object(6)
memory usage: 25.5+ KB


In [50]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM                         GPU   
0             2         3         15.6    7    6       Intel HD Graphics 620  \
1             2         6         17.3    8   16  Nvidia GeForce GTX 1050 Ti   
2             2         2         15.6    7   12       Intel HD Graphics 620   
3             2         3         13.3    6    4       Intel HD Graphics 520   
4             2         3         15.6    9    6              AMD Radeon 530   

   Weight Storage_size Storage_type Storage_size1 Storage_type1  
0  2.04kg  1000000 HDD         None       1000000           HDD  
1  2.99kg   256000 SSD      1TB HDD        256000           SSD  
2  2.19kg   512000 SSD         None        512000           SSD  
3   1.2kg   128000 SSD         None        128000           SSD  
4   2.2kg   256000 SSD         None        256000           SSD

In [51]:
pc['Storage_size1'] = pc['Storage_size1'].astype(int)

In [52]:
pc = pc.drop('Storage_size', axis=1)

In [53]:
pc['Storage_type'].unique()

array([None, '1TB HDD', '500GB HDD', '1TB Hybrid'], dtype=object)

In [54]:
pc['Storage_type'] = pc['Storage_type'].str.replace('+ ', '')

In [55]:
pc['Storage_type'].unique()

array([None, '1TB HDD', '500GB HDD', '1TB Hybrid'], dtype=object)

In [56]:
pc['Storage_type'] = pc['Storage_type'].str.replace('GB', '000')
pc['Storage_type'] = pc['Storage_type'].str.replace('TB', '000000')

In [57]:
pc['Storage_type'].unique()

array([None, '1000000 HDD', '500000 HDD', '1000000 Hybrid'], dtype=object)

In [58]:
pc['Storage_type'] = pc['Storage_type'].fillna(0)

In [59]:
pc['Storage_type'].unique()

array([0, '1000000 HDD', '500000 HDD', '1000000 Hybrid'], dtype=object)

In [60]:
pc['Storage_type'] = pc['Storage_type'].str.strip()

In [61]:
pc['Storage_type'].unique()

array([nan, '1000000 HDD', '500000 HDD', '1000000 Hybrid'], dtype=object)

In [62]:
pc['Storage_type'] = pc['Storage_type'].fillna(0)

In [63]:
pc[['Storage_size2', 'Storage_type2']] = pc['Storage_type'].str.split(' ', n=1, expand=True)

In [64]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM                         GPU   
0             2         3         15.6    7    6       Intel HD Graphics 620  \
1             2         6         17.3    8   16  Nvidia GeForce GTX 1050 Ti   
2             2         2         15.6    7   12       Intel HD Graphics 620   
3             2         3         13.3    6    4       Intel HD Graphics 520   
4             2         3         15.6    9    6              AMD Radeon 530   

   Weight Storage_type  Storage_size1 Storage_type1 Storage_size2   
0  2.04kg            0        1000000           HDD           NaN  \
1  2.99kg  1000000 HDD         256000           SSD       1000000   
2  2.19kg            0         512000           SSD           NaN   
3   1.2kg            0         128000           SSD           NaN   
4   2.2kg            0         256000           SSD           NaN   

  Storage_type2  
0           NaN  
1           HDD  
2           NaN  
3           NaN  
4           NaN

In [65]:
pc['Storage_type2'] = pc['Storage_type2'].fillna(0)

In [66]:
pc['Storage_type2'].unique()

array([0, 'HDD', 'Hybrid'], dtype=object)

In [67]:
pc['Storage_size2'].unique()

array([nan, '1000000', '500000'], dtype=object)

In [68]:
pc['Storage_size2'] = pc['Storage_size2'].fillna(0)

In [69]:
pc['Storage_size2'] = pc['Storage_size2'].astype(int)

In [70]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    object 
 7   Storage_type   325 non-null    object 
 8   Storage_size1  325 non-null    int32  
 9   Storage_type1  325 non-null    object 
 10  Storage_size2  325 non-null    int32  
 11  Storage_type2  325 non-null    object 
dtypes: float64(1), int32(4), int64(2), object(5)
memory usage: 25.5+ KB


In [71]:
pc = pc.drop('Storage_type', axis=1)

In [72]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    object 
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    object 
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    object 
dtypes: float64(1), int32(4), int64(2), object(4)
memory usage: 23.0+ KB


In [73]:
pc['Storage_type1'].unique()

array(['HDD', 'SSD', 'Hybrid', 'Flash '], dtype=object)

In [74]:
pc['Storage_type1'] = pc['Storage_type1'].str.strip()

In [75]:
pc['Storage_type1'].unique()

array(['HDD', 'SSD', 'Hybrid', 'Flash'], dtype=object)

In [76]:
pesos_discos = {
    'SSD': 4,
    'Hybrid': 3,
    'Flash': 2,
    'HDD': 1,
    'None': 0
}

In [77]:
pc['Storage_type1'] = pc['Storage_type1'].map(pesos_discos)

In [78]:
pc['Storage_type2'] = pc['Storage_type2'].map(pesos_discos)

In [79]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    object 
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  48 non-null     float64
dtypes: float64(2), int32(4), int64(3), object(2)
memory usage: 23.0+ KB


In [80]:
pc['Storage_type1'].unique()

array([1, 4, 3, 2], dtype=int64)

In [81]:
pc['Storage_type2'].unique()

array([nan,  1.,  3.])

In [82]:
pc['Storage_type2'] = pc['Storage_type2'].fillna(0)

In [83]:
pc['Storage_type2'].unique()

array([0., 1., 3.])

In [84]:
pc['Storage_type2'] = pc['Storage_type2'].astype(int)

In [85]:
pc['Storage_type2'].unique()

array([0, 1, 3])

In [86]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    object 
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    int32  
dtypes: float64(1), int32(5), int64(3), object(2)
memory usage: 21.7+ KB


In [87]:
pc.head()

Manufacturer  Category  Screen Size  CPU  RAM                         GPU   
0             2         3         15.6    7    6       Intel HD Graphics 620  \
1             2         6         17.3    8   16  Nvidia GeForce GTX 1050 Ti   
2             2         2         15.6    7   12       Intel HD Graphics 620   
3             2         3         13.3    6    4       Intel HD Graphics 520   
4             2         3         15.6    9    6              AMD Radeon 530   

   Weight  Storage_size1  Storage_type1  Storage_size2  Storage_type2  
0  2.04kg        1000000              1              0              0  
1  2.99kg         256000              4        1000000              1  
2  2.19kg         512000              4              0              0  
3   1.2kg         128000              4              0              0  
4   2.2kg         256000              4              0              0

In [88]:
pc['Weight'].unique()

array(['2.04kg', '2.99kg', '2.19kg', '1.2kg', '2.2kg', '2.3kg', '1.75kg',
       '2.25kg', '2.5kg', '2.36kg', '1.6kg', '0.97kg', '2.1kg', '1.9kg',
       '1.68kg', '1.4kg', '1.11kg', '2.4kg', '1.48kg', '2.7kg', '1.34kg',
       '2.18kg', '1.64kg', '1.95kg', '1.43kg', '2.65kg', '1.26kg',
       '1.54kg', '1.49kg', '1.5kg', '1.47kg', '2.08kg', '2.09kg',
       '2.31kg', '1.29kg', '2.63kg', '1.84kg', '1.8kg', '1.45kg',
       '3.78kg', '4.6kg', '1.1kg', '1.91kg', '1.96kg', '2.94kg', '4kgs',
       '2.32kg', '3.58kg', '1.62kg', '3.21kg', '0.920kg', '2.06kg',
       '1.3kg', '3.0kg', '0.99kg', '0.69kg', '1.7kg', '1.86kg', '2.6kg',
       '4.3kg', '2.20kg', '2.9kg', '2.59kg', '1.16kg', '2.24kg', '1.23kg',
       '1.25kg', '1.05kg', '3.52kg', '1.35kg', '2kg', '3.35kg', '2.23kg',
       '3kg', '1.88kg', '2.8kg', '2.0kg', '1.27kg', '2.62kg', '1.44kg',
       '3.31kg', '2.07kg', '1.36kg', '1.98kg', '2.591kg', '4.2kg',
       '1.15kg', '2.21kg', '2.43kg', '3.3kg', '2.191kg', '1.08kg',
       '2.7

In [89]:
pc['Weight'] = pc['Weight'].str.strip()

In [90]:
pc['Weight'] = pc['Weight'].str.replace('kg', '')

In [91]:
pc['Weight'].unique()

array(['2.04', '2.99', '2.19', '1.2', '2.2', '2.3', '1.75', '2.25', '2.5',
       '2.36', '1.6', '0.97', '2.1', '1.9', '1.68', '1.4', '1.11', '2.4',
       '1.48', '2.7', '1.34', '2.18', '1.64', '1.95', '1.43', '2.65',
       '1.26', '1.54', '1.49', '1.5', '1.47', '2.08', '2.09', '2.31',
       '1.29', '2.63', '1.84', '1.8', '1.45', '3.78', '4.6', '1.1',
       '1.91', '1.96', '2.94', '4s', '2.32', '3.58', '1.62', '3.21',
       '0.920', '2.06', '1.3', '3.0', '0.99', '0.69', '1.7', '1.86',
       '2.6', '4.3', '2.20', '2.9', '2.59', '1.16', '2.24', '1.23',
       '1.25', '1.05', '3.52', '1.35', '2', '3.35', '2.23', '3', '1.88',
       '2.8', '2.0', '1.27', '2.62', '1.44', '3.31', '2.07', '1.36',
       '1.98', '2.591', '4.2', '1.15', '2.21', '2.43', '3.3', '2.191',
       '1.08', '2.77', '2.34', '1.24', '4.0', '2.29', '1.17'],
      dtype=object)

In [93]:
pc['Weight'] = pc['Weight'].str.replace('4s', '4.5')

In [94]:
pc['Weight'] = pc['Weight'].astype(float)

In [95]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    object 
 6   Weight         325 non-null    float64
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    int32  
dtypes: float64(2), int32(5), int64(3), object(1)
memory usage: 21.7+ KB


In [96]:
pc['GPU'].unique()

array(['Intel HD Graphics 620', 'Nvidia GeForce GTX 1050 Ti',
       'Intel HD Graphics 520', 'AMD Radeon 530', 'AMD Radeon R5 M430',
       'Nvidia GeForce GTX 1060', 'AMD Radeon R7 M445',
       'Intel HD Graphics 620 ', 'Intel HD Graphics 515',
       'AMD Radeon 520', 'Intel HD Graphics 500', 'Intel HD Graphics 505',
       'Nvidia GeForce GTX 1050', 'Nvidia GeForce 930MX',
       'Nvidia Quadro 3000M', 'AMD Radeon R5', 'Intel HD Graphics 400',
       'Nvidia GeForce 930M', 'Nvidia GeForce GTX 980M',
       'Nvidia GeForce 940MX', 'Nvidia GeForce GTX 965M',
       'Intel HD Graphics', 'Nvidia GeForce GTX 980 ',
       'Nvidia GeForce GTX 970M', 'AMD Radeon R5 M330',
       'Nvidia GeForce GTX 950M', 'Nvidia GeForce GTX 1070',
       'AMD FirePro W4190M', 'Intel HD Graphics 405',
       'AMD FirePro W6150M', 'Nvidia GeForce GTX 960M', 'AMD Radeon R4',
       'AMD Radeon R5 M315', 'Intel Iris Plus Graphics 640',
       'Nvidia Quadro M500M', 'AMD Radeon R7 M360',
       'Nvidia Quadr

In [97]:
pesos_grafica = {
    'Intel HD Graphics 6000': 3,
    'Intel HD Graphics 620': 3,
    'AMD Radeon Pro 455': 4,
    'Intel Iris Plus Graphics 650': 4,
    'AMD Radeon R5': 3,
    'Intel Iris Pro Graphics': 4,
    'Nvidia GeForce MX150': 4,
    'Intel UHD Graphics 620': 3,
    'Intel HD Graphics 520': 3,
    'AMD Radeon Pro 555': 4,
    'AMD Radeon R5 M430': 3,
    'Intel HD Graphics 615': 3,
    'AMD Radeon Pro 560': 4,
    'Nvidia GeForce 940MX': 3,
    'Intel HD Graphics 400': 2,
    'Nvidia GeForce GTX 1050': 4,
    'AMD Radeon R2': 2,
    'AMD Radeon 530': 3,
    'Nvidia GeForce 930MX': 3,
    'Intel HD Graphics': 2,
    'Intel HD Graphics 500': 3,
    'Nvidia GeForce 930MX ': 3,
    'Nvidia GeForce GTX 1060': 5,
    'Nvidia GeForce 150MX': 3,
    'Intel Iris Graphics 540': 4,
    'AMD Radeon RX 580': 5,
    'Nvidia GeForce 920MX': 3,
    'AMD Radeon R4 Graphics': 2,
    'AMD Radeon 520': 3,
    'Nvidia GeForce GTX 1070': 5,
    'Nvidia GeForce GTX 1050 Ti': 4,
    'Nvidia GeForce MX130': 3,
    'AMD R4 Graphics': 2,
    'Nvidia GeForce GTX 940MX': 3,
    'AMD Radeon RX 560': 4,
    'Nvidia GeForce 920M': 2,
    'AMD Radeon R7 M445': 3,
    'AMD Radeon RX 550': 4,
    'Nvidia GeForce GTX 1050M': 4,
    'Intel HD Graphics 515': 3,
    'AMD Radeon R5 M420': 3,
    'Intel HD Graphics 505': 3,
    'Nvidia GTX 980 SLI': 5,
    'AMD R17M-M1-70': 4,
    'Nvidia GeForce GTX 1080': 5,
    'Nvidia Quadro M1200': 4,
    'Nvidia GeForce 920MX ': 2,
    'Nvidia GeForce GTX 950M': 4,
    'AMD FirePro W4190M ': 3,
    'Nvidia GeForce GTX 980M': 5,
    'Intel Iris Graphics 550': 4,
    'Nvidia GeForce 930M': 3,
    'Intel HD Graphics 630': 3,
    'AMD Radeon R5 430': 3,
    'Nvidia GeForce GTX 940M': 4,
    'Intel HD Graphics 510': 3,
    'Intel HD Graphics 405': 2,
    'AMD Radeon RX 540': 4,
    'Nvidia GeForce GT 940MX': 3,
    'AMD FirePro W5130M': 3,
    'Nvidia Quadro M2200M': 4,
    'AMD Radeon R4': 2,
    'Nvidia Quadro M620': 4,
    'AMD Radeon R7 M460': 3,
    'Intel HD Graphics 530': 4,
    'Nvidia GeForce GTX 965M': 4,
    'Nvidia GeForce GTX1080': 5,
    'Nvidia GeForce GTX1050 Ti': 4,
    'Nvidia GeForce GTX 960M': 4,
    'AMD Radeon R2 Graphics': 2,
    'Nvidia Quadro M620M': 4,
    'Nvidia GeForce GTX 970M': 4,
    'Nvidia GeForce GTX 960<U+039C>': 4,
    'Intel Graphics 620': 3,
    'Nvidia GeForce GTX 960': 4,
    'AMD Radeon R5 520': 3,
    'AMD Radeon R7 M440': 3,
    'AMD Radeon R7': 3,
    'Nvidia Quadro M520M': 4,
    'Nvidia Quadro M2200': 4,
    'Nvidia Quadro M2000M': 4,
    'Intel HD Graphics 540': 3,
    'Nvidia Quadro M1000M': 4,
    'AMD Radeon 540': 3,
    'Nvidia GeForce GTX 1070M': 5,
    'Nvidia GeForce GTX1060': 5,
    'Intel HD Graphics 5300': 2,
    'AMD Radeon R5 M420X': 3,
    'AMD Radeon R7 Graphics': 3,
    'Nvidia GeForce 920': 2,
    'Nvidia GeForce 940M': 3,
    'Nvidia GeForce GTX 930MX': 3,
    'AMD Radeon R7 M465': 3,
    'AMD Radeon R3': 2,
    'Nvidia GeForce GTX 1050Ti': 4,
    'AMD Radeon R7 M365X': 3,
    'AMD Radeon R9 M385': 4
}

In [98]:
pc['GPU'] = pc['GPU'].str.strip()

In [99]:
pc['GPU'] = pc['GPU'].map(pesos_grafica)

In [100]:
pc['GPU'].unique()

array([ 3.,  4.,  5., nan,  2.])

In [101]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            307 non-null    float64
 6   Weight         325 non-null    float64
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    int32  
dtypes: float64(3), int32(5), int64(3)
memory usage: 21.7 KB


In [102]:
pc['GPU'] = pc['GPU'].fillna(0)

In [103]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    float64
 6   Weight         325 non-null    float64
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    int32  
dtypes: float64(3), int32(5), int64(3)
memory usage: 21.7 KB


In [104]:
pc['GPU'] = pc['GPU'].astype(int)

In [105]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Manufacturer   325 non-null    int64  
 1   Category       325 non-null    int64  
 2   Screen Size    325 non-null    float64
 3   CPU            325 non-null    int32  
 4   RAM            325 non-null    int32  
 5   GPU            325 non-null    int32  
 6   Weight         325 non-null    float64
 7   Storage_size1  325 non-null    int32  
 8   Storage_type1  325 non-null    int64  
 9   Storage_size2  325 non-null    int32  
 10  Storage_type2  325 non-null    int32  
dtypes: float64(2), int32(6), int64(3)
memory usage: 20.4 KB


In [106]:
pc.to_csv('pc_test.csv', index=False)